# Generated by Django 5.0.14 on 2026-08-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('card', 'Credit/Debit Card'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
